"""estrutura inicial

Revision ID: e0229b46c0c0
Revises: 
Create Date: 2026-08-27 15:46:41.134235
"""
from alembic import op
import sqlalchemy as sa


revision = 'e0229b46c0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('stream_path', sa.String(length=120), nullable=False),
    sa.Column('tunnel_host', sa.String(length=255), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('bitrate_mbps', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=16), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_sessions_started_at'), 'flight_sessions', ['started_at'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_is_current'), 'model_metrics', ['is_current'], unique=False)
    op.create_index(op.f('ix_model_metrics_measured_at'), 'model_metrics', ['measured_at'], unique=False)
    op.create_index(op.f('ix_model_metrics_model_version'), 'model_metrics', ['model_version'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('flight_session_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('disk_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('train_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=False),
    sa.Column('embargo_seconds', sa.Integer(), nullable=False),
    sa.Column('roboflow_status', sa.String(length=16), nullable=False),
    sa.Column('roboflow_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roboflow_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_session_id'], ['flight_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_started_at'), 'datasets', ['started_at'], unique=False)
    op.create_index(op.f('ix_datasets_version'), 'datasets', ['version'], unique=True)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('flight_session_id', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flight_time_seconds', sa.Integer(), nullable=False),
    sa.Column('damage_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('asset_tag', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_session_id'], ['flight_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_code'), 'inspections', ['code'], unique=True)
    op.create_index(op.f('ix_inspections_inspected_at'), 'inspections', ['inspected_at'], unique=False)
    op.create_table('telemetry_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_fps', sa.Float(), nullable=True),
    sa.Column('inference_fps', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('bitrate_mbps', sa.Float(), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('mediamtx_up', sa.Boolean(), nullable=False),
    sa.Column('tunnel_up', sa.Boolean(), nullable=False),
    sa.Column('stream_up', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['flight_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_samples_at'), 'telemetry_samples', ['at'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_session_id'), 'telemetry_samples', ['session_id'], unique=False)
    op.create_table('damages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_reference', sa.String(length=512), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_w', sa.Float(), nullable=True),
    sa.Column('bbox_h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damages_inspection_id'), 'damages', ['inspection_id'], unique=False)
    op.create_table('dataset_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('embargoed', sa.Boolean(), nullable=False),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_images_captured_at'), 'dataset_images', ['captured_at'], unique=False)
    op.create_index(op.f('ix_dataset_images_dataset_id'), 'dataset_images', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_images_split'), 'dataset_images', ['split'], unique=False)
    op.create_table('sap_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('sap_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_notes_inspection_id'), 'sap_notes', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_sap_notes_sap_number'), 'sap_notes', ['sap_number'], unique=False)
    op.create_index(op.f('ix_sap_notes_status'), 'sap_notes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_notes_status'), table_name='sap_notes')
    op.drop_index(op.f('ix_sap_notes_sap_number'), table_name='sap_notes')
    op.drop_index(op.f('ix_sap_notes_inspection_id'), table_name='sap_notes')
    op.drop_table('sap_notes')
    op.drop_index(op.f('ix_dataset_images_split'), table_name='dataset_images')
    op.drop_index(op.f('ix_dataset_images_dataset_id'), table_name='dataset_images')
    op.drop_index(op.f('ix_dataset_images_captured_at'), table_name='dataset_images')
    op.drop_table('dataset_images')
    op.drop_index(op.f('ix_damages_inspection_id'), table_name='damages')
    op.drop_table('damages')
    op.drop_index(op.f('ix_telemetry_samples_session_id'), table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_at'), table_name='telemetry_samples')
    op.drop_table('telemetry_samples')
    op.drop_index(op.f('ix_inspections_inspected_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_code'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_datasets_version'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_started_at'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_model_metrics_model_version'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_measured_at'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_is_current'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_flight_sessions_started_at'), table_name='flight_sessions')
    op.drop_table('flight_sessions')
    op.drop_table('flight_connection')
    # ### end Alembic commands ###
